version: 1
title: My Server
layout:
    widthMode: preset
    maxWidth: 960
    customWidth: 1520
appLayout:
    size: small
appearance:
    accent: '#405dce'
    background: '#16181d'
panes:
    - id: pane-1
      label: Cool Apps
      position: 0,1
      appColumns: 6
      appRows: 3
      apps:
        - id: drive
          name: Google Drive
          position: 2,0
          url: https://drive.google.com
          icon: google-drive
        - id: app-fcee2b7b1b
          name: Test
          position: 0,1
          url: https://test.com
          icon: speedtest-light
          openInNewTab: true
